"""Add is_reserved to tables

Revision ID: 7d957df4eeea
Revises: aac55d9fdc97
Create Date: 2024-07-01 01:21:50.591671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d957df4eeea'
down_revision = 'aac55d9fdc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reserved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('is_reserved')

    # ### end Alembic commands ###
